name: 🔖 Upload build assets

on:
  push:
    tags: [ 'v*.*.*' ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup environement variables
        run: |
          pip install -r scripts/requirements.txt
          python3 scripts/definitions.py
      - name: Package datapacks
        run: python3 scripts/distribute.py -v ${{ github.ref_name }} -w 0
      - name: Package world
        uses: aksiome/minecraft-package@master
        with:
          config: .mcwpack.yml
          source: ${{ env.WORLD_PATH }}
          target: ${{ env.BUILD_PATH }}/bookshelf-world-${{ github.ref_name }}.zip
      - name: Upload artifacts
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ env.BUILD_PATH }}/*

    permissions:
      id-token: write
      contents: write
